.PHONY: all clean

CFLAGS+=
LDFLAGS+=-lm     # link to math library

TARGET1=train
TARGET2=test

all: $(TARGET1) $(TARGET2)
# type make/make all to compile test_hmm

clean:
	$(RM) $(TARGET1)   # type make clean to remove the compiled file
	$(RM) $(TARGET2)